// Views of the semantic layer (database: semanticlayer). Generated by pipeline/views.py;
// the same queries are the search phrases of views/semantic-layer.perspective.json.

// Semantic map
MATCH (d:Domain)-[c:CONTAINS]->(s:Subject)
OPTIONAL MATCH (s)-[l:LINKED]-(s2:Subject)
RETURN d, c, s, l, s2;

:params {"name": "fct_card_transactions"}
// Table $name
MATCH (t:Table {name: $name})
OPTIONAL MATCH (t)-[j:JOINS]-(o:Table)
OPTIONAL MATCH (t)-[d:DERIVED_FROM]->(src:Table)
OPTIONAL MATCH (t)-[i:IN_SUBJECT]->(s:Subject)
OPTIONAL MATCH (t)-[u:USE_INSTEAD]->(alt:Table)
RETURN t, j, o, d, src, i, s, u, alt;

:params {"a": "fct_delinquency_daily", "b": "dim_branch"}
// Join $a to $b
MATCH (a:Table {name: $a}), (b:Table {name: $b})
MATCH p = shortestPath((a)-[:JOINS*..6]-(b))
WHERE all(r IN relationships(p) WHERE NOT r.suspect)
RETURN p;

:params {"name": "fct_contacts_all"}
// Lineage of $name
MATCH p = (t:Table {name: $name})-[:DERIVED_FROM*1..6]->(:Table)
RETURN p;

:params {"name": "customer_360"}
// Who uses $name
MATCH (t:Table {name: $name})<-[c:CONSUMES]-(p:Principal)
OPTIONAL MATCH (p)-[m:MEMBER_OF]->(tm:Team)
RETURN t, c, p, m, tm;

// Traps
MATCH (t:Avoid)
WHERE coalesce(t.consumer_count, 0) > 0
OPTIONAL MATCH (t)-[u:USE_INSTEAD]->(alt:Table)
RETURN t, u, alt;

:params {"v": "Customer Key"}
// Variable $v
MATCH (v:Variable {display_name: $v})<-[i:IS]-(c:Column)<-[h:HAS_COLUMN]-(t:Table)
RETURN v, i, c, h, t;

// Customer identity
MATCH (e:Entity)<-[i:IDENTIFIES]-(v:Variable)
OPTIONAL MATCH (v)-[l:LINKED_VIA]-(v2:Variable)
RETURN e, i, v, l, v2;

// Sensitive data
MATCH (t:Table)-[h:HAS_COLUMN]->(c:Column) WHERE c.sensitive AND t.in_catalog
MATCH (t)-[d:IN_DATASET]->(ds:Dataset)
OPTIONAL MATCH (f:Finding)-[a:ABOUT]->(c)
RETURN t, h, c, d, ds, f, a;

// Suspect joins
MATCH (f:Finding {kind: 'suspect_join'})-[a:ABOUT]->(c:Column)<-[h:HAS_COLUMN]-(t:Table)
RETURN f, a, c, h, t;

:params {"name": "customer_360"}
// Copies of $name
MATCH (t:Table {name: $name})
MATCH p = (t)-[:COPY_OF*1..4]-(:Table)
RETURN p;

:params {"name": "card_spend_by_segment"}
// Findings about $name
MATCH (t:Table {name: $name})
OPTIONAL MATCH (f:Finding)-[a:ABOUT]->(t)
OPTIONAL MATCH (g:Finding)-[b:ABOUT]->(c:Column)<-[h:HAS_COLUMN]-(t)
RETURN t, f, a, g, b, c, h;
